### ISSUE TITLE
new core linux-5.10.63 can not be compiled

### ISSUE THREAD

**Issue by openips** [openwrt/packages#16622] opened 2021-09-12 22:35 UTC
with the new core  linux-5.10.63 ， errors occurred while compiling to compile failure

elf.c: In function 'read_symbols':
elf.c:407:8: error: implicit declaration of function 'gelf_getsymshndx'; did you mean 'gelf_getsym'? [-Werror=implicit-function-declaration]
  407 |   if (!gelf_getsymshndx(symtab->data, shndx_data, i, &sym->sym,
      |        ^~~~~~~~~~~~~~~~
      |        gelf_getsym
cc1: all warnings being treated as errors
make[8]: *** [/LEDE_IMG/openwrt-master/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.63/tools/build/Makefile.build:97: /LEDE_IMG/openwrt-master/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.63/tools/objtool/elf.o] Error 1
make[7]: *** [Makefile:59: /LEDE_IMG/openwrt-master/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.63/tools/objtool/objtool-in.o] Error 2
make[6]: *** [Makefile:68: objtool] Error 2
make[5]: *** [Makefile:1948: tools/objtool] Error 2
make[5]: Leaving directory '/LEDE_IMG/openwrt-master/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.63'
make[4]: *** [Makefile:22: /LEDE_IMG/openwrt-master/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.63/.modules] Error 2
make[4]: Leaving directory '/LEDE_IMG/openwrt-master/target/linux/x86'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/LEDE_IMG/openwrt-master/target/linux'
time: target/linux/compile#26.88#7.61#58.30
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/LEDE_IMG/openwrt-master'
make[1]: *** [target/Makefile:18: /LEDE_IMG/openwrt-master/staging_dir/target-x86_64_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/LEDE_IMG/openwrt-master'
make: *** [/LEDE_IMG/openwrt-master/include/toplevel.mk:230: world] Error 2

**Comment by ynezz** [comment] 2021-09-13 12:25
Wrong bug tracker, duplicate of [FS#3707](https://bugs.openwrt.org/index.php?do=details&task_id=3707)

**Closed by ynezz** 2021-09-13 12:25 UTC
