### ISSUE TITLE
Freeradius3-common: missing dependencies for the following libraries: libpcre.so.1

### ISSUE THREAD

**Issue by sharikov** [openwrt/packages#8648] opened 2019-04-10 22:08 UTC
Maintainer: Lucile Quirion lucile.quirion@savoirfairelinux.com
Environment: OpenWrt HEAD

Description:

Freeradius3-common fails to build. 

> Package freeradius3-common is missing dependencies for the following libraries:
libpcre.so.1<

Tried again with fresh install of Ubuntu 18.04.2 LTS and new OpenWrt build, and it fails again.

**Comment by neheb** [comment] 2019-04-11 08:51
Ping @yangfl

**Comment by yangfl** [comment] 2019-04-13 11:37
No idea. `make package/freeradius3/compile` fine on openwrt-sdk-18.06.2-ar71xx-generic_gcc-7.3.0_musl.Linux-x86_64

**Comment by Robby-** [comment] 2019-04-13 12:40
@yangfl: I'm experiencing this same problem on the master branch, which is probably what the OP meant.
I'm compiling on Debian 9.8, however.

**Comment by yangfl** [comment] 2019-04-13 13:42
Debian sid, but I don't think this could be related to build os. Adding a dep will probably work, but I won't have time/env to test that.

**Comment by neheb** [comment] 2019-04-13 21:12
Could not reproduce on Ubuntu 18.04. Might be some oddity with freeradius where it's picking up some host library.

**Comment by Robby-** [comment] 2019-04-13 22:40
Well, I can test that because I was preparing a PR to update freeradius3 to the latest stable version anyway.

I'm a bit confused because there is already a dependency set on it via `+PACKAGE_libpcre:libpcre` and although it seems erroneous, it did compile fine with this about 8 months ago, not sure what made it break as I can't seem to find anything related. However, I'll include a fix for this issue in my PR.

**Comment by neheb** [comment] 2019-04-14 04:53
There's a similar issue on the buildbots where gammu has a similar dependency on bluez-libs.

My theory is that there's a race condition since the buildbots run their make jobs in parallel. Basically libpcre gets built after the dependencies get resolved and freeradius picks it up.

When it comes to this dependency, it should be either set to off or on.

**Comment by Robby-** [comment] 2019-04-16 15:17
@neheb: I submitted a PR (#8681) that includes a fix for this issue. If you could take a look at it please.

**Closed** 2019-04-17 18:36 UTC

**Comment by sharikov** [comment] 2019-04-17 21:02
Thanks so much everyone and thanks for the fix @Robby-.
