### ISSUE TITLE
SIGILL when running node.js (MIPS, AR9331)

### ISSUE THREAD

**Issue by schmist** [openwrt/packages#1937] opened 2015-11-09 10:05 UTC
Running node returns `Illegal Instruction`. Enabling FPU emulation resolves the issue. It seems that the V8 version for the packaged node (0.12.7) does not support soft floats anymore.

**Comment by yaseenox** [comment] 2015-12-24 14:22
I have the same problem, did you figure it out ?

**Comment by yaseenox** [comment] 2015-12-27 09:47
How can I enable FPU emulation ?

**Comment by karlp** [comment] 2016-05-24 09:08
Duplicate of https://github.com/openwrt/packages/issues/2633

**Comment by hnyman** [comment] 2016-08-26 11:23
closing as duplicate

**Closed by hnyman** 2016-08-26 11:23 UTC
