### ISSUE TITLE
DDNS requiring package update while ddns-scripts already at most recent version

### ISSUE THREAD

**Issue by Borromini** [openwrt/packages#1285] opened 2015-05-22 19:13 UTC
I ran a build on a trunk checkout from yesterday (May 21st), and the LuCI DDNS package is complaining about the ddns-scripts package not being the most recent version. However, it's at 2.4.2, which is the latest.

![schermafdruk van 2015-05-22 21 05 46](https://cloud.githubusercontent.com/assets/8218431/7777899/29826d10-00c7-11e5-9795-16f22301ce6f.png)

**Comment by db260179** [comment] 2015-05-23 07:02
The change of min version in the luci-app-ddns seems to be the cause of this

+DDNS_MIN = "2.4.2-1"	-- minimum version of service required

Previously
-DDNS_MIN = "2.2.0-1"	-- minimum version of service required
Doesnt show this error

**Comment by chris5560** [comment] 2015-05-24 17:59
Not an issue of ddns-scripts.
Will be fixed in luci-app-ddns 2.2.4-1.
Christian

**Closed** 2015-07-27 21:56 UTC
