### ISSUE TITLE
pptpd can not start via /etc/init.d/pptpd start

### ISSUE THREAD

**Issue by rufengsuixing** [openwrt/packages#9554] opened 2019-07-24 00:12 UTC
Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: openwrt 18.06.4

Description:

pptpd can not start via /etc/init.d/pptpd start
can start via ssh

**Comment by feckert** [comment] 2019-08-13 07:30
Please add a description how to reproduce this issue.

**Comment by neheb** [comment] 2020-01-28 04:53
It's not starting because "enabled" is 0 in /etc/config/pptpd . Closing.

**Closed by neheb** 2020-01-28 04:53 UTC
