### ISSUE TITLE
Fix etherwake for musl compiling?

### ISSUE THREAD

**Issue by danielpetre** [openwrt/packages#1433] opened 2015-06-19 09:10 UTC
Hello, can you please fix for musl compiling? Thanks!

make[3]: Entering directory '/home/dani/openwrt/feeds/packages/net/etherwake'
mipsel-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -D__UCLIBC__ /home/dani/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.10/etherwake-1.09.orig/ether-wake.c -o /home/dani/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.10/etherwake-1.09.orig/etherwake
In file included from /home/dani/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_musl-1.1.10/include/netinet/ether.h:8:0,
                 from /home/dani/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.10/etherwake-1.09.orig/ether-wake.c:94:
/home/dani/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_musl-1.1.10/include/netinet/if_ether.h:96:8: error: redefinition of 'struct ethhdr'
 struct ethhdr {
        ^
In file included from /home/dani/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.10/etherwake-1.09.orig/ether-wake.c:91:0:
/home/dani/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_musl-1.1.10/include/linux/if_ether.h:137:8: note: originally defined here
 struct ethhdr {
        ^
Makefile:55: recipe for target '/home/dani/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.10/etherwake-1.09.orig/.built' failed
make[3]: *** [/home/dani/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.10/etherwake-1.09.orig/.built] Error 1
make[3]: Leaving directory '/home/dani/openwrt/feeds/packages/net/etherwake'
package/Makefile:191: recipe for target 'package/feeds/packages/etherwake/compile' failed
make[2]: *** [package/feeds/packages/etherwake/compile] Error 2
make[2]: Leaving directory '/home/dani/openwrt'
package/Makefile:188: recipe for target '/home/dani/openwrt/staging_dir/target-mipsel_24kec+dsp_musl-1.1.10/stamp/.package_compile' failed
make[1]: *** [/home/dani/openwrt/staging_dir/target-mipsel_24kec+dsp_musl-1.1.10/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/dani/openwrt'
/home/dani/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by Noltari** [comment] 2015-06-19 09:51
Duplicate of https://github.com/openwrt/packages/issues/1381
Fix proposed by jow on https://github.com/openwrt/packages/pull/1387

**Closed by Noltari** 2015-06-19 09:51 UTC
