### ISSUE TITLE
tdb: split package into two packages - libtdb and tdb-utils

### ISSUE THREAD

**Issue by LLE8** [openwrt/packages#5792] opened 2018-03-20 08:17 UTC
Maintainer: @pfzim 
Environment: LEDE 17.01.4

I think it may save space on target device, if tdbtool, tdbbackup, tdbdump, tdbrestore are not required.

**Comment by diizzyy** [comment] 2018-07-05 08:01
@LLE8 
Please do a pull request or close this issue as it's not a bug.

**Closed** 2018-08-17 14:59 UTC
