### ISSUE TITLE
Luci-proto-bonding related compatibility issues

### ISSUE THREAD

**Issue by qiuzi** [openwrt/packages#15223] opened 2021-03-22 12:07 UTC
Using the latest version of luci source code results in list slaves'eth2'

And proto_config_add_string "slaves" does not support list variables

**Comment by he-ma** [comment] 2021-04-06 10:32
@qiuzi
Hi,
I'm absolutely not sure what you mean.
Could you please detail which version of luci you use, what do you mean by `results in list slaves'eth2'` 
and how you got the error you describe.
Some pics could also be useful.

Regards
Helge

**Comment by qiuzi** [comment] 2021-04-06 13:18
@he-ma 
https://github.com/openwrt/luci/blob/master/protocols/luci-proto-bonding/htdocs/luci-static/resources/protocol/bonding.js#L177
https://github.com/openwrt/packages/blob/master/net/bonding/files/lib/netifd/proto/bonding.sh#L40 
not compatible with luci

**Comment by qiuzi** [comment] 2021-04-06 14:32
![image](https://user-images.githubusercontent.com/1689784/113723279-c59d4500-9723-11eb-80ea-6f2e8b100433.png)

**Comment by he-ma** [comment] 2021-04-08 11:30
Sorry, but I couldn't reproduce your problem.
I set up a new machine and used luci based up to the commit dated on Apr 6, 2021.
Below some screenshots which show the functionality still working.
![11](https://user-images.githubusercontent.com/26056858/114019018-351f4b80-986e-11eb-8f5d-37dcd79fee59.png)
![22](https://user-images.githubusercontent.com/26056858/114019020-35b7e200-986e-11eb-9709-be17b048ed7e.png)
![33](https://user-images.githubusercontent.com/26056858/114019022-36507880-986e-11eb-933e-a4578a8d9de4.png)
![44](https://user-images.githubusercontent.com/26056858/114019288-80395e80-986e-11eb-93db-e930ca2a12c2.png)
![55](https://user-images.githubusercontent.com/26056858/114019028-36e90f00-986e-11eb-9867-4dbb647269ce.png)
![66](https://user-images.githubusercontent.com/26056858/114019030-36e90f00-986e-11eb-969f-5ab0e18cbeab.png)

**Comment by qiuzi** [comment] 2021-04-08 13:06
@he-ma 
 `ubus call network.interface.test status`
```
{
        "up": true,
        "pending": false,
        "available": true,
        "autostart": true,
        "dynamic": false,
        "uptime": 993,
        "l3_device": "bonding-test",
        "proto": "bonding",
        "updated": [
                "addresses"
        ],
        "metric": 0,
        "dns_metric": 0,
        "delegation": true,
        "ipv4-address": [
                {
                        "address": "111.111.111.111",
                        "mask": 24
                }
        ],
        "ipv6-address": [

        ],
        "ipv6-prefix": [

        ],
        "ipv6-prefix-assignment": [

        ],
        "route": [

        ],
        "dns-server": [

        ],
        "dns-search": [

        ],
        "neighbors": [

        ],
        "inactive": {
                "ipv4-address": [

                ],
                "ipv6-address": [

                ],
                "route": [

                ],
                "dns-server": [

                ],
                "dns-search": [

                ],
                "neighbors": [

                ]
        },
        "data": {

        }
}

```
no device information found
how is your output?

**Comment by he-ma** [comment] 2021-04-08 14:13
Well, exept the 'uptime' and 'address' values (of course) it's the same.
If you have a look at `ubus call bonding status` you'll see the slaves.

But I think that's all beyond your initial issue that LuCI won't work.

**Comment by qiuzi** [comment] 2021-04-08 17:20
@he-ma 
https://github.com/openwrt/packages/blob/master/net/bonding/files/lib/netifd/proto/bonding.sh#L160
```
	local slaves
	json_get_vars slaves
	echo "$slaves" >> /tmp/1.txt
```
Adding the output on line 160, I get an empty 1.txt file
Variables are not output correctly

/etc/config/network
```
config interface 'test'
	option proto 'bonding'
	option ipaddr '121.0.1.1'
	option netmask '255.255.255.0'
	option slaves 'eth2 eth3'
	option bonding_policy 'balance-rr'
	option packets_per_slave '1'
	option xmit_hash_policy 'layer2'
	option all_slaves_active '0'
	option link_monitoring 'off'

```
/tmp/1.txt
```


eth2 eth3
eth2
eth3
```
cat /sys/class/net/bonding-test/bonding/slaves
eth2 eth3

**Comment by qiuzi** [comment] 2021-04-09 04:30
@he-ma 
Use vmware to load the image, the problem can be reproduced
[openwrt-x86-64-generic-squashfs-combined.zip](https://github.com/openwrt/packages/files/6283155/openwrt-x86-64-generic-squashfs-combined.zip)

**Comment by he-ma** [comment] 2021-04-09 08:45
@qiuzi
Sorry, I have no vmware.
As I wrote yesterday, the LuCI and the script to set up the bonding stuff -at least for me- works.
I don't know why your config file now has `option`  for the slaves as initially you had (the correct) `list`

I fear I can't help you anymore as I can't see/can't reproduce any misbehaviour.

**Comment by feckert** [comment] 2021-04-13 07:38
Fixed with https://github.com/openwrt/packages/commit/57a77386de7dda12f60bf3021efcde7f059833c8

**Closed by feckert** 2021-04-13 07:38 UTC
