### ISSUE TITLE
xl2tpd does not reconnect

### ISSUE THREAD

**Issue by uk3** [openwrt/packages#1661] opened 2015-08-16 21:04 UTC
Hello,

I observed the following problem in current trunk: When my l2tp tunnel gets disconnected for some reason, it does not reconnect automatically.

Only after a click in the gui the tunnel reconnects (immediately without problems).

**Comment by yousong** [comment] 2015-08-21 01:35
Duplicate of #1334 .  Close it for now.

**Closed by yousong** 2015-08-21 01:35 UTC
