### ISSUE TITLE
ocserv-1.1.3-1: requires non-existing libatomic1 package

### ISSUE THREAD

**Issue by mmokrejs** [openwrt/packages#15953] opened 2021-06-25 23:35 UTC
Maintainer: @nmav

```
Details for package ocserv

    Version: 1.1.3-1
    Size: ~234.8 KB installed
    Dependencies:
        libhttp-parser (14.7 KB) Not installed
        libgnutls (912.6 KB) Not installed
            libnettle8 (306.1 KB) Not installed
                libgmp10 (185.3 KB) Not installed
            libatomic1 Not available
        certtool (130.9 KB) Not installed
        libncurses6 Installed
            terminfo Installed
        libreadline8 Installed
            libncurses6 Installed
        libprotobuf-c (8.9 KB) Not installed
        libev (21.2 KB) Not installed
        kmod-tun Installed
            kernel Installed

Description

OpenConnect server (ocserv) is an SSL VPN server. Its purpose is to be a secure, small, fast and configurable VPN server. It implements the OpenConnect SSL VPN protocol, and has also (currently experimental) compatibility with clients using the AnyConnect SSL VPN protocol. The OpenConnect VPN protocol uses the standard IETF security protocols such as TLS 1.2, and Datagram TLS to provide the secure VPN service.

    Required dependency package libatomic1 is not available in any repository.
```

Likewise the client part

```
Details for package openconnect

    Version: 8.10-3
    Size: ~118.3 KB installed
    Dependencies:
        libxml2 (468.2 KB) Not installed
            libpthread Installed
                libgcc1 Installed
            zlib Installed
        kmod-tun Installed
            kernel Installed
        resolveip (1.5 KB) Not installed
        vpnc-scripts (2.3 KB) Not installed
        libgnutls (912.6 KB) Not installed
            libnettle8 (306.1 KB) Not installed
                libgmp10 (185.3 KB) Not installed
            libatomic1 Not available
        libtasn1 (29.8 KB) Not installed

Description

A VPN client compatible with several SSL VPN implementations (ocserv, Cisco AnyConnect, Juniper, Palo Alto) OpenConnect is an SSL VPN client initially created to support Cisco's AnyConnect SSL VPN. It has since been extended to support the Pulse Connect Secure VPN (formerly known as Juniper Network Connect or Junos Pulse) and the Palo Alto Networks GlobalProtect SSL VPN. A corresponding OpenConnect VPN server implementation can be found in the ocserv package.

    Required dependency package libatomic1 is not available in any repository.

Overwrite files from other package(s)

```

Powered by LuCI openwrt-21.02 branch (git-21.163.64918-ba57ec5) / OpenWrt 21.02.0-rc3 r16172-2aba3e9784 

Model | Netgear Nighthawk X4S R7800
Architecture | ARMv7 Processor rev 0 (v7l)
Kernel Version | 5.4.124

**Comment by mmokrejs** [comment] 2022-05-22 13:41
I did not build the package, I just installed it from the repo. I do not know why the repo did not contain the required dependency.

**Comment by nmav** [comment] 2023-09-10 13:35
Closing for now. Please reopen if the issue is still there.

**Closed by nmav** 2023-09-10 13:35 UTC
