### ISSUE TITLE
nginx-full not working properly

### ISSUE THREAD

**Issue by zcy85611** [openwrt/packages#20999] opened 2023-05-12 11:59 UTC
after sovle the compile issue, now nginx-full can be compiled

but it fails to start because missing "/etc/nginx/uwsgi_params", add the file from old compile, nginx starts

Thu May 11 01:13:20 2023 daemon.err nginx_init: 2023/05/11 01:13:20 [emerg] 4746#0: open() "/etc/nginx/uwsgi_params" failed (2: No such file or directory) in /etc/nginx/conf.d/luci.locations:3
Thu May 11 01:13:20 2023 daemon.err nginx_init: nginx: configuration file /etc/nginx/uci.conf test failed
Thu May 11 01:13:20 2023 daemon.err nginx_init: NOT using conf file!

and after add webdav configuration, even with "nginx-mod-dav-ext" installed, it still tells "unknown directive "dav_ext_lock_zone"

it seems that nginx-mod-dav-ext is not working at all

Thu May 11 01:12:30 2023 daemon.err nginx_init: 2023/05/11 01:12:29 [emerg] 4699#0: unknown directive "dav_ext_lock_zone" in /etc/nginx/conf.d/webdav.conf:1
Thu May 11 01:12:30 2023 daemon.err nginx_init: nginx: configuration file /etc/nginx/uci.conf test failed
Thu May 11 01:12:30 2023 daemon.err nginx_init: NOT using conf file!

webdav configuration file works on old compile

could you help to look into this please? thanks

**Comment by Ansuel** [comment] 2023-05-12 12:01
you need to load the module for dav ext to correctly work.

for uwsgi i'm checking

**Comment by zcy85611** [comment] 2023-05-12 12:03
> you need to load the module for dav ext to correctly work.
> 
> for uwsgi i'm checking

may I ask how to load the module? and is it possible to do it automaticly like the old ones?

**Comment by Ansuel** [comment] 2023-05-12 12:04
nginx documentation, there is nothing special here actually we are aligning on how things works in the rest of the world (debian, ubuntu)

**Comment by zcy85611** [comment] 2023-05-12 12:27
> nginx documentation, there is nothing special here actually we are aligning on how things works in the rest of the world (debian, ubuntu)

ok, I know how to load module now, thanks for the help

**Comment by Ansuel** [comment] 2023-05-12 12:28
@zcy85611 Nice! And sorry for the breakage... it's something we had to do for a long time so these regression are saddly needed.

**Comment by zcy85611** [comment] 2023-05-12 13:45
> @zcy85611 Nice! And sorry for the breakage... it's something we had to do for a long time so these regression are saddly needed.

it's okay, thanks for keeping improving the codes

**Comment by sjkhsl** [comment] 2023-06-13 04:40
> @zcy85611 Nice! And sorry for the breakage... it's something we had to do for a long time so these regression are saddly needed.

23.05 After the nginx is built, there are still problems，23.05 is still missing two patches commit 7b91373 commit f5d7a26，It is normal in master。

**Comment by Ansuel** [comment] 2023-06-13 08:37
@sjkhsl please wait the new version of nginx to be built... also those 2 commit are not needed

**Comment by alex3d** [comment] 2023-08-31 19:32
`uwsgi_params` and some other config files are missing in`nginx-full` package due to typo in Makefile.
This should be fixed when https://github.com/openwrt/packages/pull/21985 gets merged.

**Closed** 2023-09-01 01:55 UTC
