### ISSUE TITLE
<all-packages> lose in mipsel_24kc devices

### ISSUE THREAD

**Issue by h2y** [openwrt/packages#6026] opened 2018-05-09 13:33 UTC
Environment: MT7621 (mipsel_24kc)

Description:

<https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/>

The opkg repo become empty for all mipsel_24kc devices.

it is a same issue to <https://bugs.openwrt.org/index.php?do=details&task_id=1538>

**Comment by jow-** [comment] 2018-05-09 13:38
Duplicate of https://bugs.openwrt.org/index.php?do=details&task_id=1538

**Closed by jow-** 2018-05-09 13:38 UTC

**Comment by h2y** [comment] 2018-05-10 00:11
the status is uncomfirm till now. and the error didn't fixed.

**Comment by luizluca** [comment] 2018-05-10 06:59
@h2y, those kind of bugs that affect base packages must go to https://bugs.openwrt.org. No need to duplicate reports. It looks like it is now fixed.

**Comment by kugland** [comment] 2019-06-20 23:59
It's happening again.
