### ISSUE TITLE
i2c-tools: build failed on ubuntu 18.04

### ISSUE THREAD

**Issue by ptpt52** [openwrt/packages#21164] opened 2023-05-25 00:13 UTC
```
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/Data/Sources/openwrt/x-wrt/tmpfs/target-mipsel_24kc_musl/i2c-tools-4.3'
cd "/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/i2c-tools-4.3" && CC="mipsel-openwrt-linux-musl-gcc" CCSHARED="mipsel-openwrt-linux-musl-gcc -DPIC -fpic" CXX="mipsel-openwrt-linux-musl-g++" LD="mipsel-openwrt-linux-musl-gcc" LDSHARED="mipsel-openwrt-linux-musl-gcc -shared" CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/i2c-tools-4.3=i2c-tools-4.3 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CPPFLAGS="-I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/usr/include -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/include/fortify -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/include -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-mipsel_24kc_musl/usr/include/python3.11" LDFLAGS="-L/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/usr/lib -L/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/lib -znow -zrelro -lpython3.11" _PYTHON_HOST_PLATFORM="linux-mipsel" __PYVENV_LAUNCHER__="/usr/bin/python3.11" PYTHONPATH="/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-mipsel_24kc_musl/usr/lib/python3.11:/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-mipsel_24kc_musl//usr/lib/python3.11/site-packages:/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/i2c-tools-4.3/ipkg-install//usr/lib/python3.11/site-packages" PYTHONDONTWRITEBYTECODE=1 _python_sysroot="/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-mipsel_24kc_musl" _python_prefix="/usr" _python_exec_prefix="/usr"    /mnt/Data/Sources/openwrt/x-wrt/staging_dir/hostpkg/bin/python3.11  -m build --no-isolation --outdir "/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/i2c-tools-4.3/py-smbus"/openwrt-build --wheel   "/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/i2c-tools-4.3/py-smbus" 
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-mipsel_24kc_musl/usr/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3.11'

ERROR Backend operation failed: FileNotFoundError(2, 'No such file or directory')
Makefile:108: recipe for target '/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/i2c-tools-4.3/.built' failed
make[2]: *** [/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-mipsel_24kc_musl/i2c-tools-4.3/.built] Error 1
make[2]: Leaving directory '/mnt/Data/Sources/openwrt/openwrt-feeds/packages/utils/i2c-tools'
time: package/feeds/packages/i2c-tools/compile#0.35#0.09#0.43
    ERROR: package/feeds/packages/i2c-tools failed to build.
package/Makefile:118: recipe for target 'package/feeds/packages/i2c-tools/compile' failed
make[1]: *** [package/feeds/packages/i2c-tools/compile] Error 1
make[1]: Leaving directory '/mnt/Data/Sources/openwrt/x-wrt'
/mnt/Data/Sources/openwrt/x-wrt/include/toplevel.mk:229: recipe for target 'package/feeds/packages/i2c-tools/compile' failed
make: *** [package/feeds/packages/i2c-tools/compile] Error 2
```

**Comment by jefferyto** [comment] 2023-05-25 02:36
Duplicate of #21162.

**Closed by jefferyto** 2023-05-25 02:36 UTC
