### ISSUE TITLE
libjpeg and libjpeg-turbo discussion

### ISSUE THREAD

**Issue by stefaang** [openwrt/packages#10090] opened 2019-09-27 09:04 UTC
On the jpeg-turbo website:
2019-02-04: libjpeg-turbo Becomes Official ISO/ITU-T Reference Implementation

My proposal is to revert the libjpeg version from 9c to 8c as it is the default in several major linux distros and this paves the way for the libjpeg-turbo package. It does require to recompile at least about 20 packages that depend on libjpeg though.

e.g. Ubuntu has these packages: libjpeg-dev (8c, default), libjpeg62 (1.6b2), libjpeg8 (8c) and libjpeg9 (9b).

I've done some basic tests with the python [jpegtran-cffi](https://pypi.org/project/jpegtran-cffi/) library which requires [epeg](https://github.com/mattes/epeg) and [jpeg-turbo](https://libjpeg-turbo.org/) on entware on an ARMv7 dual core. I used https://github.com/openwrt/packages/pull/6331 as a basis.
My script with jpegtran provides about a 2x to 10x speedup for thumbnail generation for my owncloud/nextcloud instance on a single core.. 
This change meant that user experience for browsing Pictures went from terrible (10s+ load time) to acceptable (1s).

TBH, I was not sure if this discussion belongs in the Entware repo or here. They have less platforms to support so I'm willing to move if necessary.

**Comment by lucize** [comment] 2019-09-29 06:46
I have jpeg-turbo ready here https://github.com/openwrt/packages/pull/8314

**Comment by neheb** [comment] 2019-09-29 20:19
Reverting to 8c needs to be done in a pull request.

Going to libjpeg-turbo is long overdue. openembedded and buildroot already have.

**Comment by stefaang** [comment] 2019-09-30 08:24
Here's how buildroot does it: https://git.busybox.net/buildroot/tree/package/jpeg/Config.in
You need to choose between JIG libjpeg and jpeg-turbo. 
I assume you can setup a similar choice in the config here... I'll need to dig up some examples and come up with a proposal PR.

**Comment by diizzyy** [comment] 2019-10-01 06:46
To my knowledge the issue is that it doesn't compile on a few "exotic" platforms or at least used to and little not no interest doing platform specific workarounds regarding libraries.

**Comment by neheb** [comment] 2020-01-22 02:24
Relevant: https://github.com/openwrt/packages/pull/11017

-turbo is much faster.

**Comment by neheb** [comment] 2020-08-01 03:46
I have now merged this.

**Closed by neheb** 2020-08-01 03:46 UTC
