### ISSUE TITLE
config errors/warnings caused by host-build.mk being included twice by python3 

### ISSUE THREAD

**Issue by Peng-Hua** [openwrt/packages#3430] opened 2016-11-01 01:40 UTC
Input the command "./scripts/feeds install -p openvswitch"

Why does appear ：
package/Makefile:196: warning: overriding commands for target ‵package/feeds/packages/python3/host/clean'
package/Makefile:196: warning: ignoring old commands for target `package/feeds/packages/python3/host/clean'
package/Makefile:196: warning: overriding commands for target `package/feeds/packages/python3/host/download'
package/Makefile:196: warning: ignoring old commands for target `package/feeds/packages/python3/host/download'
package/Makefile:196: warning: overriding commands for target `package/feeds/packages/python3/host/prepare'
package/Makefile:196: warning: ignoring old commands for target `package/feeds/packages/python3/host/prepare'
package/Makefile:196: warning: overriding commands for target `package/feeds/packages/python3/host/compile'
package/Makefile:196: warning: ignoring old commands for target `package/feeds/packages/python3/host/compile'
package/Makefile:196: warning: overriding commands for target `package/feeds/packages/python3/host/install'
package/Makefile:196: warning: ignoring old commands for target `package/feeds/packages/python3/host/install'
package/Makefile:196: warning: overriding commands for target `package/feeds/packages/python3/host/update'
package/Makefile:196: warning: ignoring old commands for target `package/feeds/packages/python3/host/update'

It did not appear this problem 3 days ago,
I would like to ask what the problem is,
Thanks a lot.

**Comment by yousong** [comment] 2016-11-01 06:10
It is caused by `host-build.mk` being included twice by python3 package and `BUILD_TYPES` have two duplicate values `host`.

**Comment by yousong** [comment] 2016-11-01 06:10
ping python3's current maintainer ;) @commodo

**Comment by commodo** [comment] 2016-11-01 06:50
yeah ; my bad for that too
will fix :)

[ when it rains, it pours [i guess] ]

**Comment by Peng-Hua** [comment] 2016-11-01 06:58
Thank you so much~ : )

**Comment by yousong** [comment] 2016-11-01 07:14
> [ when it rains, it pours [i guess] ]

Well, I am thinking of a similar saying in Chinese "屋漏偏逢连夜雨", which means literally "the rain pours for days without ending when the roof was just broken and leaky" ;)

That said, maybe we can add a include guard for host-build.mk just like what has been done for target.mk.  Even a warning can help if including twice the Makefile is not considered a good practice.

**Comment by commodo** [comment] 2016-11-01 07:19
was also thinking about a guard like that too ; tho, I am/was unsure whether to propose it, since it's in LEDE core
i think for python packages it may also make sense to do this 
so, i'll do them for python-*.mk files [and adapt it from target.mk, or maybe just wing it]

**Comment by commodo** [comment] 2016-11-01 07:51
so i was wondering, if we should reset all these python,python3 issues to moving 
```
HOST_BUILD_PREFIX:=$(if $(IS_PACKAGE_BUILD),$(STAGING_DIR)/host,$(STAGING_DIR_HOST))
```
in rules.mk  (away from host-build.mk) and not having to include host-build.mk in python-package.mk/python3-package.mk 

this story started with the change of HOST_BUILD_PREFIX;
and it looks like `STAGING_DIR`, `STAGING_DIR_HOST` & `IS_PACKAGE_BUILD` is part of `rules.mk`, which makes HOST_BUILD_PREFIX a shorthand for these 3

sorry, for not noticing this earlier

@hnyman @yousong @NeoRaider ?

**Comment by commodo** [comment] 2016-11-01 08:05
RFC: https://github.com/lede-project/source/pull/465

**Comment by commodo** [comment] 2016-11-01 12:21
referencing PR from @jow- https://github.com/openwrt/packages/pull/3433
when this gets merged, it should fix the issue

**Closed** 2016-11-01 12:35 UTC
