### ISSUE TITLE
please reconfigure "shadowsocks-libev"

### ISSUE THREAD

**Issue by mzhboy** [openwrt/packages#2026] opened 2015-11-26 12:42 UTC
@aa65535  please reconfigure `shadowsocks-libev`, we need `ss-local` and `ss-server`.

**Comment by yousong** [comment] 2016-08-13 06:30
@mzhboy , please consider opening a pull request.  I also made a package of shadowsocks-libev myself and I think it's worth a try.

**Comment by yousong** [comment] 2016-09-01 08:48
Close this one as it seems that the issue is not going to receive any further responses.  If you are still interested in it, I would suggest contacting directly with the current maintainer.

**Closed by yousong** 2016-09-01 08:48 UTC
Labels: waiting for maintainer
