### ISSUE TITLE
mc (midnight commander) - package missing in TRUNK

### ISSUE THREAD

**Issue by camelcamro** [openwrt/packages#7349] opened 2018-11-08 10:06 UTC
mc (midnight commander) - package missing in TRUNK
only available in stable builds which is very old, but in trunk missing

**Comment by dibdot** [comment] 2018-11-08 13:18
Duplicate of #7180 ... probably I will disable VFS support (again) with the next mc update as long as the underlying librpc issue has not been fixed.

**Closed by dibdot** 2018-11-08 13:18 UTC

**Comment by dibdot** [comment] 2018-11-11 17:33
done, let's see if buildbot is happy again ...;-)
