### ISSUE TITLE
make menuconfig report 'WARNING: Makefile 'package/feeds/packages/postgresql/Makefile' has a build dependency on 'zlib/host', which does not exist'

### ISSUE THREAD

**Issue by ptpt52** [openwrt/packages#8410] opened 2019-03-14 06:49 UTC
latest code
make menuconfig
report:
```
WARNING: Makefile 'package/feeds/packages/postgresql/Makefile' has a build dependency on 'zlib/host', which does not exist
```

**Comment by BKPepe** [comment] 2019-03-14 07:00
Duplicate of https://github.com/openwrt/packages/issues/8393

**Closed** 2019-03-14 07:06 UTC
