### ISSUE TITLE
tmux fails to allow connection due to bad locale

### ISSUE THREAD

**Issue by ghost** [openwrt/packages#2900] opened 2016-06-27 01:15 UTC
@mstorchak 

Attempting to ssh to a device which automatically starts tmux on login from ubuntu, results in the following error message:
tmux: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968

It appears tmux locale handing has changed and broken.

**Comment by dfc-d** [comment] 2016-06-27 01:17
Actually this affects console and manual launch as well.

**Comment by mstorchak** [comment] 2016-07-05 05:48
If I set LC_CTYPE to "ANSI_X3.4-1968", tmux still works for me, both old 2.0 on the main system and 2.2 in a chroot.
@dfc-d, please explain how to reproduce the issue.

**Comment by dfc-d** [comment] 2016-07-06 02:12
On Mon, 2016-07-04 at 22:48 -0700, mstorchak wrote:
> If I set LC_CTYPE to "ANSI_X3.4-1968", tmux still works for me, both
> old 2.0 on the main system and 2.2 in a chroot.
> @dfc-d, please explain how to reproduce the issue.

Hmmmm...


On Ubuntu 16.04:

export LC_CTYPE='ANSI_X3.4-1968'
bash: warning: setlocale: LC_CTYPE: cannot change locale (ANSI_X3.4-
1968): No such file or directory

And I see no way to generate that locale via dpkg-reconfigure locales.

Basically the problem is that the ANSI locale is not universally
available and Ubuntu at least is almost exclusive UTF-8 with some
legacy ISO locales.

Regards,

Daniel

**Comment by dfc-d** [comment] 2016-08-10 05:33
@mstorchak Did you see my Ubuntu comment?

**Comment by mstorchak** [comment] 2016-08-11 14:52
I did, but I don't see how it helps to understand the root cause, I'm sorry.
tmux requires UTF-8 locale, "and Ubuntu at least is almost exclusive UTF-8", so everything is fine?

If not, please explain how to reproduce the issue.

Looks like the change in tmux in question is https://github.com/tmux/tmux/commit/0d6de44a37755f0e5046c04e19e4506a6d59e750, so only check method is different, but not the check subject itself.

**Comment by dfc-d** [comment] 2016-08-13 18:24
What I try to ssh to the device from Ubuntu 16.04 tmux: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968 when I try to use tmux.

When I attempt to set Ubuntu local to ANSI_X.4-1968 I get the above error.

My Ubuntu locale is UTF-8.en_CA (LANG=en_CA.UTF-8), default configuration

So I ought to be in a UTF-8 locale.  Perhaps this issue is that Ubuntu doesn't include LC_CTYPE=UTF-8.en_CA in the environemnt?  I will investigate that possiblity later.

**Comment by VeggieMeat** [comment] 2016-08-16 01:45
You might try re-installing the locales package. I had a similar issue after upgrading to Debian Stretch, and that resolved it.

**Comment by chinawrj** [comment] 2016-09-27 01:09
@dfc-d Hi, Did you compile OpenWRT under ubuntu 16.04; I found the same issue when I compile the source code with ubuntu 16.04. But it was OK when I compiled with ubuntu 14.04

```
tmux: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968
```

**Comment by dfc-d** [comment] 2016-09-29 07:37
I did build with 16.04 but a more recent build (newer trunk) no longer gives me this issues; not sure if the issue was solved by an update....
Do you still see the problem against latest trunk (another possibility it that the fix is in LEDE trunk rather but not OpenWrt trunk).

**Comment by diizzyy** [comment] 2017-06-02 12:03
@hnyman 
This seems resolved, close?

**Closed** 2017-06-02 12:05 UTC

**Comment by jerome-diver** [comment] 2017-06-19 01:17
it is not, when i try to connect ssh with command linked tmux for attach it to a session, i have the same error.
My locales are fine in server remote computer and server side... together on archlinux.
i don't understand what is this ANSI_X3.4-1968 here ? where this is coming from ? 
when i just connect ssh all is ok... and when i call tmux on remote computer (or server side), all is ok...so why this happen ? is it a bug ?

**Comment by cwbs** [comment] 2017-07-16 12:09
I connected via ssh on archlinux and also have these errors: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968

**Comment by raphaunix** [comment] 2017-08-27 21:02
This worked for me:

```
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen 
locale-gen 
```
Enjoy.

**Comment by zokl** [comment] 2018-03-02 14:11
I have the same problem but only if I compile openwrt image with glibc library. ulibc work fine. Do you know where is the problem?

**Comment by princeofdream** [comment] 2021-04-15 07:04
openwrt build with glibc does not have locale config files.
we should copy the locale files and regenerate locale info.

# 1. copy files from staging_dir/toolchain-xxx_glibc
``
cd staging_dir/toolchain-xxx_glibc
cp -rP bin/locale ${rootfs}/bin/
cp bin/localedef ${rootfs}/bin/
cp share ${rootfs}/bin/
``
# 2. make dirs for generate files
``
mkdir -p /usr/lib/locale/locale-archive/
mkdir -p /lib/locale/
``

# 3. regenerate locale config
``
localedef -v -c -i en_US -f UTF-8 en_US.UTF-8
``
then export TERM=xterm to run tmux
it works for me, but I try a minimal build and do the steps, it does not works well.

**Comment by princeofdream** [comment] 2021-04-15 07:14
openwrt build with glibc does not have locale config files.
we should copy the locale files and regenerate locale info.

# 1. copy files from staging_dir/toolchain-xxx_glibc
``
cd staging_dir/toolchain-xxx_glibc
cp -rP bin/locale ${rootfs}/bin/
cp bin/localedef ${rootfs}/bin/
cp share ${rootfs}/bin/
``
# 2. make dirs for generate files
``
mkdir -p /usr/lib/locale/locale-archive/
mkdir -p /lib/locale/
``

# 3. regenerate locale config
``
localedef -v -c -i en_US -f UTF-8 en_US.UTF-8
``
then export TERM=xterm to run tmux
it works for me, but I try a minimal build and do the steps, it does not works well.

**Comment by zokl** [comment] 2021-06-23 10:16
> openwrt build with glibc does not have locale config files.
> we should copy the locale files and regenerate locale info.
> 
> # 1. copy files from staging_dir/toolchain-xxx_glibc
> `cd staging_dir/toolchain-xxx_glibc cp -rP bin/locale ${rootfs}/bin/ ; cp bin/localedef ${rootfs}/bin/ ; cp sbin/* ${rootfs}/sbin/ ; cp share ${rootfs}/bin/ ;`
> 
> # 2. make dirs for generate files
> `mkdir -p /usr/lib/locale/locale-archive/ ; mkdir -p /lib/locale/`
> 
> # 3. regenerate locale config
> `localedef -v -c -i en_US -f UTF-8 en_US.UTF-8`
> 
> then reboot;
> after that export TERM=xterm to run tmux
> it works for me

Thank you, I will try it.

**Comment by zokl** [comment] 2021-06-24 07:28
Thank you very much. Your process works. I made it in the following way and put it into my makefile:

package install section:
```
	$(INSTALL_DIR) $(1)/bin
	$(INSTALL_BIN) $(TOOLCHAIN_DIR)/bin/locale $(1)/bin/
	$(INSTALL_BIN) $(TOOLCHAIN_DIR)/bin/localedef $(1)/bin/

	$(INSTALL_DIR) $(1)/usr/share
	$(CP) $(TOOLCHAIN_DIR)/share/i18n $(1)/usr/share/
```

On the machine:
```
mkdir -p /usr/lib/locale/locale-archive/ 
mkdir -p /lib/locale/

I18NPATH="/usr/share/i18n" localedef -v -c -i en_US -f UTF-8 en_US.UTF-8

```

**Comment by bobguerra** [comment] 2021-09-07 21:06
you might not want to remotely use your Linux machine with your PowerShell with Tmux just say'n
