### ISSUE TITLE
Python 3 not compiling on powerpc

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10553] opened 2019-11-15 18:28 UTC
Maintainer: @commodo @jefferyto 
Environment: master

https://downloads.openwrt.org/snapshots/faillogs/powerpc_464fp/packages/python3/compile.txt

**Comment by jefferyto** [comment] 2019-11-16 11:16
Duplicate of #10552.

**Closed** 2019-11-16 17:15 UTC
