### ISSUE TITLE
mwan3: interface with metric > 256 is not active in policy

### ISSUE THREAD

**Issue by kubco2** [openwrt/packages#4428] opened 2017-06-02 19:28 UTC
Maintainer: @Adze1502 
Environment: ar71xx, TP-Link TL-WR1043, OpenWRT 15.05

Description:
If I have only one active online interface with metric > 256, Interface is initialized except policy rules and therefore it uses fallback as policy. If I set lower value, it properly setup policy rules.

It should work for any metric value allowed by linux, or at least print error message. In LuCI member setup range 1-1000 is allowed, so it should be adjusted to unlimited or 256 according to mwan3 fix.

**Comment by feckert** [comment] 2017-08-02 12:23
@kubco2 adze1502 is no longer the maintainer of mwan3. I have agreed to do this work now. I will have a look what the problem is

**Comment by feckert** [comment] 2017-08-11 15:31
@kubco2 is your version openwrt 15.05? Could you test lede-17.01 because there were a lot of changes in the mwan3.

**Comment by feckert** [comment] 2017-11-03 07:54
@kubco2 ping?
could we close this issue?

**Comment by kubco2** [comment] 2017-11-03 08:02
Will test this weekend.

S pozdravom,
Jakub Janco

On Nov 3, 2017 08:54, "Florian Eckert" <notifications@github.com> wrote:

@kubco2 <https://github.com/kubco2> ping?
could we close this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openwrt/packages/issues/4428#issuecomment-341639685>,
or mute the thread

**Comment by kubco2** [comment] 2017-11-28 20:48
it has same problems. I created pull request for mwan3 part.

**Comment by feckert** [comment] 2017-12-18 09:40
@kubco2 I think we could close this issue?

**Closed** 2017-12-18 09:48 UTC

**Comment by feckert** [comment] 2017-12-18 09:51
@kubco2 thanks for your changes on mwan3 :-)
