### ISSUE TITLE
crtmpserver compile/build error

### ISSUE THREAD

**Issue by build000** [openwrt/packages#3321] opened 2016-10-09 14:11 UTC
@heil @sdwalker 
LEDE r1814; WNDR4700 (powerpc)
make -j1 V=s
```
(...)
make[3]: Entering directory '/home/sj/Pulpit/Projekty/WNDR4700/LEDE/feeds/packages/multimedia/crtmpserver'
make   -C /home/sj/Pulpit/Projekty/WNDR4700/LEDE/build_dir/target-powerpc_464fp_musl-1.1.15/crtmpserver-2012-07-18+git-b6fdcdb953d1e99c48a0c37a8c80f2cad2db443b/builders/make PLATFORM=linux-openwrt-uclibc -Wno-error -j6
make[4]: Entering directory '/home/sj/Pulpit/Projekty/WNDR4700/LEDE/build_dir/target-powerpc_464fp_musl-1.1.15/crtmpserver-2012-07-18+git-b6fdcdb953d1e99c48a0c37a8c80f2cad2db443b/builders/make'
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/applestreamingclient/include -c ../../sources/applications/applestreamingclient/src/clientcontext.cpp -o ../../sources/applications/applestreamingclient/src/clientcontext.applestreamingclient.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/flvplayback/include -c ../../sources/applications/flvplayback/src/httpappprotocolhandler.cpp -o ../../sources/applications/flvplayback/src/httpappprotocolhandler.flvplayback.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/flvplayback/include -c ../../sources/applications/flvplayback/src/rawhttpstreamappprotocolhandler.cpp -o ../../sources/applications/flvplayback/src/rawhttpstreamappprotocolhandler.flvplayback.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/flvplayback/include -c ../../sources/applications/flvplayback/src/mmsappprotocolhandler.cpp -o ../../sources/applications/flvplayback/src/mmsappprotocolhandler.flvplayback.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/flvplayback/include -c ../../sources/applications/flvplayback/src/rtmpappprotocolhandler.cpp -o ../../sources/applications/flvplayback/src/rtmpappprotocolhandler.flvplayback.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/flvplayback/include -c ../../sources/applications/flvplayback/src/liveflvappprotocolhandler.cpp -o ../../sources/applications/flvplayback/src/liveflvappprotocolhandler.flvplayback.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/flvplayback/include -c ../../sources/applications/flvplayback/src/rtpappprotocolhandler.cpp -o ../../sources/applications/flvplayback/src/rtpappprotocolhandler.flvplayback.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/proxypublish/include -c ../../sources/applications/proxypublish/src/rtspappprotocolhandler.cpp -o ../../sources/applications/proxypublish/src/rtspappprotocolhandler.proxypublish.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/proxypublish/include -c ../../sources/applications/proxypublish/src/proxypublishapplication.cpp -o ../../sources/applications/proxypublish/src/proxypublishapplication.proxypublish.o
../../sources/applications/applestreamingclient/src/clientcontext.cpp: In member function 'bool app_applestreamingclient::ClientContext::ConsumeAVBuffer()':
../../sources/applications/applestreamingclient/src/clientcontext.cpp:389:29: error: 'class InNetTSStream' has no member named 'GetFeedTime'
   _firstFeedTime = pStream->GetFeedTime();
                             ^
../../sources/applications/applestreamingclient/src/clientcontext.cpp:393:44: error: 'class InNetTSStream' has no member named 'GetFeedTime'
  while ((wallClockDelta + 1000 > (pStream->GetFeedTime() - _firstFeedTime)) &&
                                            ^
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/proxypublish/include -c ../../sources/applications/proxypublish/src/jobstimerappprotocolhandler.cpp -o ../../sources/applications/proxypublish/src/jobstimerappprotocolhandler.proxypublish.o
powerpc-openwrt-linux-musl-g++ -fPIC -O2  -DLINUX -DLITTLE_ENDIAN_BYTE_ALIGNED -DNET_SELECT -DCreateRTCPPacket=CreateRTCPPacket_mystyle_only_once -DFeedDataAudioMPEG4Generic=FeedDataAudioMPEG4Generic_one_by_one -DHandleTSVideoData=HandleVideoData_version3 -DHAS_PROTOCOL_HTTP -DHAS_PROTOCOL_RTMP -DHAS_PROTOCOL_LIVEFLV -DHAS_PROTOCOL_RTP -DHAS_PROTOCOL_TS -DHAS_PROTOCOL_VAR -DHAS_PROTOCOL_CLI -DHAS_PROTOCOL_HLS -DHAS_PROTOCOL_RAWHTTPSTREAM -DHAS_LUA -DHAS_MEDIA_MP3 -DHAS_MEDIA_MP4 -DHAS_MEDIA_FLV -DHAS_MEDIA_NSV -DHAS_SYSLOG -I../../3rdparty/lua-dev -I../../3rdparty/tinyxml -I/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/usr/include -I../../sources/common/include -I../../sources/thelib/include -I../../sources/applications/proxypublish/include -c ../../sources/applications/proxypublish/src/jobstimerprotocol.cpp -o ../../sources/applications/proxypublish/src/jobstimerprotocol.proxypublish.o
apps.mk:27: recipe for target '../../sources/applications/applestreamingclient/src/clientcontext.applestreamingclient.o' failed
make[4]: *** [../../sources/applications/applestreamingclient/src/clientcontext.applestreamingclient.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/sj/Pulpit/Projekty/WNDR4700/LEDE/build_dir/target-powerpc_464fp_musl-1.1.15/crtmpserver-2012-07-18+git-b6fdcdb953d1e99c48a0c37a8c80f2cad2db443b/builders/make'
Makefile:97: recipe for target '/home/sj/Pulpit/Projekty/WNDR4700/LEDE/build_dir/target-powerpc_464fp_musl-1.1.15/crtmpserver-2012-07-18+git-b6fdcdb953d1e99c48a0c37a8c80f2cad2db443b/.built' failed
make[3]: *** [/home/sj/Pulpit/Projekty/WNDR4700/LEDE/build_dir/target-powerpc_464fp_musl-1.1.15/crtmpserver-2012-07-18+git-b6fdcdb953d1e99c48a0c37a8c80f2cad2db443b/.built] Error 2
make[3]: Leaving directory '/home/sj/Pulpit/Projekty/WNDR4700/LEDE/feeds/packages/multimedia/crtmpserver'
package/Makefile:127: recipe for target 'package/feeds/packages/crtmpserver/compile' failed
make[2]: *** [package/feeds/packages/crtmpserver/compile] Error 2
make[2]: Leaving directory '/home/sj/Pulpit/Projekty/WNDR4700/LEDE'
package/Makefile:124: recipe for target '/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/home/sj/Pulpit/Projekty/WNDR4700/LEDE/staging_dir/target-powerpc_464fp_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/sj/Pulpit/Projekty/WNDR4700/LEDE'
/home/sj/Pulpit/Projekty/WNDR4700/LEDE/include/toplevel.mk:193: polecenia dla obiektu 'world' nie powiodły się
make: *** [world] Błąd 2
```

**Comment by thess** [comment] 2016-10-13 13:47
Duplicate of #3183

**Closed by thess** 2016-10-13 13:47 UTC
Labels: duplicate
