### ISSUE TITLE
gpsd: Build fails due to missing -lncurses flag

### ISSUE THREAD

**Issue by deltahotel** [openwrt/packages#3710] opened 2016-12-27 15:47 UTC
Maintainer: @psidhu 
Environment: LEDE lede-project/source@d3489d899a, packages c785ad3, mips-24k

Description:

`make package/gpsd/compile` fails with due to unresolved symbols:

cgps.o: In function \`die':
cgps.c:(.text+0x2): undefined reference to \`isendwin'
cgps.c:(.text+0x7c): undefined reference to \`mvcur'
cgps.c:(.text+0x82): undefined reference to \`echo'
cgps.c:(.text+0x88): undefined reference to \`endwin'
cgps.c:(.text+0xa8): undefined reference to \`LINES'
cgps.c:(.text+0xac): undefined reference to \`COLS'
…

Both `gpsd` as well as `libncurses` were selected as `m` (module) and `libncurses` is indeed available. Adding an `-lncurses` flag to gcc's options resolves the problem so it's seems it's just this flag which is missing.

**Comment by RussellSenior** [comment] 2017-01-20 06:38
@deltahotel I am seeing this on an up-to-date ArchLinux build host, but not on a fresh checkout on Ubuntu 16.04.  The problem seems to be in the scons detection of the ncurses library.  On Ubuntu the cgps compile command line ends in -lncurses -ltinfo, but these are missing on the ArchLinux build host.

**Comment by RussellSenior** [comment] 2017-01-20 18:25
@deltahotel @psidhu #3888 should fix it.

See: https://github.com/openwrt/packages/pull/3888

**Comment by deltahotel** [comment] 2017-01-22 12:06
Sounds plausible since I was using Arch as well. Thanks for the research and the patch, @RussellSenior! I'll close this issue once your PR is merged.

**Comment by psidhu** [comment] 2017-01-23 16:19
@deltahotel Please test.

**Comment by glycoknob** [comment] 2017-02-19 14:38
Works fine on current Arch, could this be backported to the 17.01 branch?

**Comment by deltahotel** [comment] 2017-03-29 20:38
@psidhu Compilation works fine for me, thanks for the fix! I'll leave the issue open for the moment since @glycoknob's comment is still unanswered.

**Comment by glycoknob** [comment] 2017-05-08 05:25
The issue is still open - there is already a pull request waiting for almost two weeks: https://github.com/openwrt/packages/pull/4300 - is there any problem merging this or is everyone busy / overworked? This breaks building an image with olsr for for all ncurses6 distros at the moment.

**Comment by hnyman** [comment] 2017-05-08 07:16
#4300 was merged. Closing this.

**Closed by hnyman** 2017-05-08 07:16 UTC
