### ISSUE TITLE
<uhttpd on mbedtls> does not load anymore a certificate chain (intermediate CA)

### ISSUE THREAD

**Issue by farfade** [openwrt/packages#22441] opened 2023-10-18 14:45 UTC
@cotequeiroz

Environment: ramips/mt7621 23.05.0

Hello,

Description:

I face a regression starting from version 23, compared to version 22, for loading into uhttpd a certificate *chain* (with an intermediate certificate authority)

In version 22, I was using a standard PEM formatted certificate chain. All was simple and went well.

In version 23, I face the error "uhttpd: Failed to load certificate/key files".

This is a first problem : losing the ability to use PEM (text) certs. 

The second problem is that I tried to use DER as the documentation there https://openwrt.org/docs/guide-user/luci/getting_rid_of_luci_https_certificate_warnings says 

```openssl x509 -in /etc/letsencrypt/live/example.com/fullchain.pem -outform DER -out /tmp/uhttpd```

But it does not work neither : it only includes the first certificate of fullchain.pem (but not the full chain) in the DER output.
It means that in spite of having the DER certificate loaded by uhttpd, the user faces an error because the servers does not send any more the intermediate certificate.

Trying some well-known workarounds : embedding the chain into a PKCS7 package; or concatenating the intermediate cert as DER to the leaf cert as DER does not work neither.

It may be a regression due to the switch to mbedtls (but they advertise it supports PEM, so I think the problem comes from uhttpd).

Thanks for reading,

farfade

**Comment by jow-** [comment] 2023-10-19 12:08
Duplicate of of #13728

**Closed by jow-** 2023-10-19 12:08 UTC
