### ISSUE TITLE
python3 not compiling on hardfloat mips

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#17417] opened 2021-12-22 01:36 UTC
Maintainer: @commodo @jefferyto 

https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc_24kf/packages/python3/compile.txt

**Comment by jefferyto** [comment] 2021-12-22 05:05
Duplicate of #17217.

**Closed** 2021-12-22 05:19 UTC
