### ISSUE TITLE
adblock-[2.5.1]"can not load full block lists on my wndr4300 router"

### ISSUE THREAD

**Issue by jack338c** [openwrt/packages#4258] opened 2017-04-13 07:58 UTC
Maintainer: Dirk Brenken <dev@brenken.org>
Environment: LEDE Reboot SNAPSHOT r3956-ffd055d on Router Wndr4300

Description:

# Here are logs of adblock and system logs of router,someone tell me how to solve this ,thank you

Wed Apr 12 22:09:09 2017 user.notice adblock-[2.5.1] info : start adblock processing ...
Wed Apr 12 22:09:09 2017 user.notice adblock-[2.5.1] debug: name: adaway, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 125084
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: adaway, mode: backup, count: 379, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: adguard, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: blacklist, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: disconnect, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 125084
Wed Apr 12 22:09:21 2017 user.notice adblock-[2.5.1] debug: name: disconnect, mode: backup, count: 5119, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: dshield, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: feodo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: hphosts, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: malware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: malwarelist, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: openphish, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: palevo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: ransomware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_ch, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_pl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_ro, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_ru, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: securemecca, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: shalla, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: spam404, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: sysctl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: whocares, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: winspy, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: winhelp, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: yoyo, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 125084
Wed Apr 12 22:09:26 2017 user.notice adblock-[2.5.1] debug: name: yoyo, mode: backup, count: 2319, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:26 2017 user.notice adblock-[2.5.1] debug: name: zeus, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:31 2017 user.notice adblock-[2.5.1] info : block lists with overall 5549 domains loaded successfully (LEDE Reboot SNAPSHOT r3956-ffd055d)

# system logs of router

Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: disconnect, mode: backup, count: 5119, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: dshield, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: feodo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: hphosts, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: malware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: malwarelist, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: openphish, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: palevo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: ransomware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: reg_ch, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: reg_pl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: reg_ro, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: reg_ru, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: securemecca, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: shalla, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: spam404, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:58 2017 user.notice adblock-[2.5.1] debug: name: sysctl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:59 2017 user.notice adblock-[2.5.1] debug: name: whocares, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:59 2017 user.notice adblock-[2.5.1] debug: name: winspy, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:59 2017 user.notice adblock-[2.5.1] debug: name: winhelp, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:08:59 2017 user.notice adblock-[2.5.1] debug: name: yoyo, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 125084
Wed Apr 12 22:09:03 2017 user.notice adblock-[2.5.1] debug: name: yoyo, mode: backup, count: 2319, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:03 2017 user.notice adblock-[2.5.1] debug: name: zeus, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:04 2017 daemon.info dnsmasq[7661]: exiting on receipt of SIGTERM
Wed Apr 12 22:09:08 2017 user.notice adblock-[2.5.1] info : block lists with overall 5549 domains loaded successfully (LEDE Reboot SNAPSHOT r3956-ffd055d)
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: started, version 2.77test4 cachesize 150
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: DNS service limited to local subnets
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC no-ID loop-detect inotify
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq-dhcp[8049]: DHCP, IP range 192.168.11.100 -- 192.168.11.249, lease time 12h
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain test
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain onion
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain localhost
Wed Apr 12 22:09:09 2017 user.notice adblock-[2.5.1] info : start adblock processing ...
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain local
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain invalid
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain example.net
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain example.org
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain example.com
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zzux.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zzcartoon.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zyzg.us 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zyzc9.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zyns.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zynamics.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zynaima.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zvereff.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zuola.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zuo.la 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zuobiao.me 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zsrhao.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zshare.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zozotown.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zoozle.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zootool.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zonghexinwen.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zonghexinwen.com 
Wed Apr 12 22:09:09 2017 user.notice adblock-[2.5.1] debug: name: adaway, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 125084
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zonaeuropa.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zomobo.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zodgame.us 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zmw.cn 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zkaip.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain ziporn.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain ziplib.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zinio.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zillionk.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain ziddu.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zh.wiktionary.org 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zh.wikivoyage.org 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using 2 more local addresses
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using 10357 more nameservers
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: reading /tmp/resolv.conf.auto
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain test
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain onion
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain localhost
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain local
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain invalid
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain example.net
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain example.org
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using local addresses only for domain example.com
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zzux.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zzcartoon.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zyzg.us 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zyzc9.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zyns.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zynamics.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zynaima.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zvereff.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zuola.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zuo.la 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zuobiao.me 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zsrhao.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zshare.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zozotown.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zoozle.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zootool.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zonghexinwen.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zonghexinwen.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zonaeuropa.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zomobo.net 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zodgame.us 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zmw.cn 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zkaip.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain ziporn.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain ziplib.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zinio.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zillionk.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain ziddu.com 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zh.wiktionary.org 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using nameserver 127.0.0.1#7453 for domain zh.wikivoyage.org 
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using 2 more local addresses
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: using 10359 more nameservers
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: read /etc/hosts - 4 addresses
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: read /tmp/hosts/dhcp.cfg02411c - 2 addresses
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq[8049]: read /tmp/hosts/odhcpd - 2 addresses
Wed Apr 12 22:09:09 2017 daemon.info dnsmasq-dhcp[8049]: read /etc/ethers - 0 addresses
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: adaway, mode: backup, count: 379, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: adguard, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: blacklist, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:11 2017 user.notice adblock-[2.5.1] debug: name: disconnect, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 125084
Wed Apr 12 22:09:21 2017 user.notice adblock-[2.5.1] debug: name: disconnect, mode: backup, count: 5119, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: dshield, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: feodo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: hphosts, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: malware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: malwarelist, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: openphish, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: palevo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: ransomware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_ch, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_pl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_ro, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: reg_ru, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: securemecca, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: shalla, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: spam404, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: sysctl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: whocares, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: winspy, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: winhelp, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:22 2017 user.notice adblock-[2.5.1] debug: name: yoyo, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 125084
Wed Apr 12 22:09:26 2017 user.notice adblock-[2.5.1] debug: name: yoyo, mode: backup, count: 2319, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:26 2017 user.notice adblock-[2.5.1] debug: name: zeus, mode: remove, count: 0, in_rc: 0, out_rc: 0
Wed Apr 12 22:09:27 2017 daemon.info dnsmasq[8049]: exiting on receipt of SIGTERM
Wed Apr 12 22:09:28 2017 authpriv.info dropbear[8260]: Child connection from 192.168.11.179:32769
Wed Apr 12 22:09:30 2017 authpriv.notice dropbear[8260]: Password auth succeeded for 'root' from 192.168.11.179:32769
Wed Apr 12 22:09:31 2017 user.notice adblock-[2.5.1] info : block lists with overall 5549 domains loaded successfully (LEDE Reboot SNAPSHOT r3956-ffd055d)
Wed Apr 12 22:09:32 2017 daemon.info dnsmasq[8314]: started, version 2.77test4 cachesize 150
Wed Apr 12 22:09:32 2017 daemon.info dnsmasq[8314]: DNS service limited to local subnets

**Comment by dibdot** [comment] 2017-04-13 08:54
@jack338c Maybe I miss something ... what's your problem actually?
To enable/disable blocklists edit /etc/config/adblock (via ssh session or via LUCI app). BTW, release 2.6.0 is the current version.

**Comment by jack338c** [comment] 2017-04-13 10:00
sorry,I did tell in details
please find above log,it should load lists 379+5119+2319=7817 (adaway disconnect yoyo),but actually are 5549. 2268 lists are not load

thank you dibdot

**Comment by dibdot** [comment] 2017-04-13 12:16
@jack338c This is not a bug, it's a feature!
adblock supports overall sort (make all lists entries unique/remove duplicates) and includes a feature called "top level domain compression" which eliminates subdomains when the top level is already in the list. 
This save valuable space for the dns backends.

Please close this one & happy blocking! :smiley:

**Comment by jack338c** [comment] 2017-04-13 13:07
hi dibdot
actually,same setting for adblock on my another router dir505 is working fine
the difference is my wndr4300's dnsmasq works pdnsd ,ipset etc
So I want to know is there a way to optimize adblock or dnsmasq to solve my problem
thank you dibdot

# here is the logs on my another router dir505 and it's working fine

Thu Apr 13 20:57:37 2017 user.notice adblock-[2.4.0-2] info : start adblock processing ...
Thu Apr 13 20:57:37 2017 user.notice adblock-[2.4.0-2] debug: name: adaway, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 60444
Thu Apr 13 20:57:49 2017 user.notice adblock-[2.4.0-2] debug: name: adaway, mode: backup, count: 379, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:49 2017 user.notice adblock-[2.4.0-2] debug: name: adguard, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:49 2017 user.notice adblock-[2.4.0-2] debug: name: blacklist, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:49 2017 user.notice adblock-[2.4.0-2] debug: name: disconnect, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 60444
Thu Apr 13 20:57:56 2017 user.notice adblock-[2.4.0-2] debug: name: disconnect, mode: backup, count: 5116, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:56 2017 user.notice adblock-[2.4.0-2] debug: name: dshield, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: feodo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: hphosts, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: malware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: malwarelist, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: openphish, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: palevo, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: ransomware, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: reg_ch, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: reg_pl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: reg_ro, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: reg_ru, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: securemecca, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: shalla, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: spam404, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: sysctl, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: whocares, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: winspy, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: winhelp, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:57:57 2017 user.notice adblock-[2.4.0-2] debug: name: yoyo, enabled: 1, backup: 1, dns: dnsmasq, fetch: /usr/bin/wget, memory: 60444
Thu Apr 13 20:58:02 2017 user.notice adblock-[2.4.0-2] debug: name: yoyo, mode: backup, count: 2319, in_rc: 0, out_rc: 0
Thu Apr 13 20:58:02 2017 user.notice adblock-[2.4.0-2] debug: name: zeus, mode: remove, count: 0, in_rc: 0, out_rc: 0
Thu Apr 13 20:58:02 2017 daemon.info dnsmasq[2421]: exiting on receipt of SIGTERM
Thu Apr 13 20:58:06 2017 user.notice adblock-[2.4.0-2] info : block lists with overall 7814 domains loaded successfully (LEDE Reboot 17.01-SNAPSHOT r3305-c6e7998)

**Comment by dibdot** [comment] 2017-04-13 14:54
@jack338c As I said before, you have no problem - protection level on both routers is the same. Your  second router has only < 64 MByte RAM. Adblock enables overall sort/duplicate removal only on devices with > 64MB RAM, this prevents sort related kernel dumps.

**Comment by jack338c** [comment] 2017-04-13 22:43
ok, I got it
thank you very much for your help

**Closed** 2017-04-13 22:43 UTC
