### ISSUE TITLE
gpsd : error in final stage

### ISSUE THREAD

**Issue by artynet** [openwrt/packages#2065] opened 2015-12-01 18:33 UTC
Hello guys, I have bumped into this issue when building the **gpsd** package. I borrowed it from the main trunk and put in my custom fork of AA 1209 and CC 1505. I get this error at the end of the process (when the IPK file is being created) : 

```
Install file: "gpsd" as "ipkg-install/usr/sbin/gpsd"
strip ipkg-install/usr/sbin/gpsd
strip: Unable to recognise the format of the input file `ipkg-install/usr/sbin/gpsd'
scons: *** [ipkg-install/usr/sbin/gpsd] Error 1
scons: building terminated because of errors.
```
Just FYI, while working on the AA fork, I first updated **SCons** to the **2.3.1** version (borrowing it from the CC stable feed) since a major version than **2.1.0** is required to start the build process. Please let me know if some of you can help me since the package builds fine in the main trunk.

Regards, Arturo

**Comment by artynet** [comment] 2015-12-01 23:46
I have just solved it by myself ! Just using the code from the **BB** packages repo and updating the source version to 3.14 :

http://goo.gl/xvq9G8

just added a dependency to libgpsd (+libgps). Now I can finally build the package on the "good 'ol" attitude adjustment :+1: . The **SCons** dependency still stands for v3.15 since it requires **v2.3** or higher to properly configure the sources.

Thank you anyway of course ! ! !

**Comment by mhei** [comment] 2015-12-27 12:55
Looks like the problem is solved, so I'm going to close this issue.

**Closed by mhei** 2015-12-27 12:55 UTC
