### ISSUE TITLE
Luci ddns error

### ISSUE THREAD

**Issue by mauriceklein** [openwrt/packages#2188] opened 2015-12-26 20:15 UTC
Hello,
if i try to safe my new ddns configuration by clicking the save button,i get this error:

/usr/lib/lua/luci/dispatcher.lua:452: Failed to execute cbi dispatcher target for entry '/admin/services/ddns/detail/myddns_ipv6'.
The called action terminated with an exception:
/usr/lib/lua/luci/tools/ddns.lua:170: unhandled validate error
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:452: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

I reeinstalled the Luci ddns package and also the ddns scripts package and i flashed the whole router with openwrt and i didn't keep the settings but nothing helped.

I've installed luci-app-ddns 2.2.4-1 and ddns-scripts 2.5.0-2.

**Comment by hnyman** [comment] 2016-01-02 09:58
This is a duplicate of  https://github.com/openwrt/luci/issues/611 and has been fixed by https://github.com/openwrt/luci/pull/616

**Closed by hnyman** 2016-01-02 09:58 UTC
