### ISSUE TITLE
node crash on mips (AR9330)

### ISSUE THREAD

**Issue by zoobab** [openwrt/packages#2442] opened 2016-02-29 15:05 UTC
Hi,

Node is crashing when I try to do a simple hello world on a MIPS target:

```
root@OpenWrt:/tmp# cat /root/hello-nodejs.js 
console.log("Hello World");
root@OpenWrt:/tmp# node /root/hello-nodejs.js 
Illegal instruction
root@OpenWrt:/tmp# node -v
v0.12.7
```

I am building it on a r48724, and compiling the same and executing it on x64 target works fine:

```
~ # node -v
v0.12.7
~ # node /root/hello.js 
Hello World
```

For the record, I try on a GL150:

```
root@OpenWrt:/tmp# cat /proc/cpuinfo 
system type             : Atheros AR9330 rev 1
machine                 : GL AR150
processor               : 0
cpu model               : MIPS 24Kc V7.4
BogoMIPS                : 265.42
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 16
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by tpham3783** [comment] 2016-02-29 15:37
​Ben,

Can you make sure software floating point is supported in the kernel.  I
got the same error the other day and enabling softfloat had solved it.


-tp

**Comment by tpham3783** [comment] 2016-02-29 15:50
​Check to see if this config is enabled while building your target firmware:

CONFIG_SOFT_FLOAT=y

**Comment by zoobab** [comment] 2016-02-29 15:52
Yes, it is enabled:

zoobab@esivisu /home/zoobab/soft/openwrt [16]$ grep "CONFIG_SOFT_FLOAT" .config
CONFIG_SOFT_FLOAT=y

I could quickly check if I have the same problem with nodejs+15.05.

**Comment by tpham3783** [comment] 2016-02-29 15:58
​Please make sure that this option is enabled in the kernel too, its under
kernel type->MIPS FPU Emulation.


CONFIG_MIPS_FPU_EMULATOR=y

**Comment by zoobab** [comment] 2016-02-29 17:29
Yeah, now that works. Is it necessary to change the node package for this problem?

**Comment by tpham3783** [comment] 2016-02-29 17:36
​Great!


It is actually a target/board config.  Some targets will support hardfloat,
some will support softfloat, others by default wont support any.  Its a
good idea to enable softfloat emulation by default for all targets if no
hard-float is detected in the target CPU.  I'll leave it up to the
developers as to how to enable the feature.

**Comment by karlp** [comment] 2016-05-24 08:57
Duplicate of https://github.com/openwrt/packages/issues/2633 ?

**Comment by diizzyy** [comment] 2017-06-02 12:21
@zoobab 
Is this still an issue or is it fixed?

**Comment by diizzyy** [comment] 2017-06-09 08:44
Problem/Solution explained in #2633 
@thess @hnyman @NeoRaider 
Please close this

**Closed** 2018-01-26 07:56 UTC
