### ISSUE TITLE
freeradius3 packages missing for openwrt 23.05.0

### ISSUE THREAD

**Issue by trustno1foxm** [openwrt/packages#22575] opened 2023-11-01 12:50 UTC
There are no freeradius3* packages for aarch64_generic architecture. For other architectures they are available. I would really need them ;) Thanks for fixing.

so long

**Comment by ynezz** [comment] 2023-11-01 12:51
Duplicate of https://github.com/openwrt/packages/issues/22574 :)

**Comment by trustno1foxm** [comment] 2023-11-01 12:51
sorry^^ thx

**Closed by ynezz** 2023-11-01 12:51 UTC
