### ISSUE TITLE
Both 23.05 and master have recursive dependencies

### ISSUE THREAD

**Issue by sjkhsl** [openwrt/packages#22302] opened 2023-10-04 17:35 UTC
make menuconfig

```
Collecting package info: done
tmp/.config-package.in:34293:error: recursive dependency detected!
tmp/.config-package.in:34293:   symbol PACKAGE_python3-pymysql depends on PYTHON3_PYMYSQL_SHA_PASSWORD_SUPPORT
feeds/packages/lang/python/pymysql/Config.in:4: symbol PYTHON3_PYMYSQL_SHA_PASSWORD_SUPPORT depends on PACKAGE_python3-pymysql
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
```

**Comment by ptpt52** [comment] 2023-10-05 02:54
same issue on master HEAD.

**Comment by BKPepe** [comment] 2023-10-05 05:26
Next time, please use specific subject instead of vague subject.

Duplicate of https://github.com/openwrt/packages/issues/22250 , closing.

**Closed by BKPepe** 2023-10-05 05:26 UTC
