### ISSUE TITLE
Add delve Go debugger package?

### ISSUE THREAD

**Issue by nwidger** [openwrt/packages#15813] opened 2021-06-09 13:19 UTC
I work on a Go application that runs on OpenWrt and have found using the [Delve](https://github.com/go-delve/delve) debugger very helpful for remote debugging.  I was able to trivially make a delve package with a few minor modifications to the Makefile in [this issue](https://github.com/openwrt/packages/issues/7639) (mainly just updating the version to 1.6.1 and using the new repo URL).  Is this a package that could make it's way into this repository?  @jefferyto, if I'm not mistaken you seem to be the maintainer for Go support in this repo, is this something I could help you with?

**Comment by jefferyto** [comment] 2021-06-11 09:24
I'm sure you are aware that the issue you mentioned (#7639) was a duplicate of #7127, and this latter issue was fixed.

AFAIK the original poster in #7639 did not open a pull request to submit their package to the repo - they only reported an issue that affected their custom package. Feel free to open a pull request for your package.

**Closed** 2021-06-11 14:51 UTC
