### ISSUE TITLE
syslog-ng: conflicts with logd package

### ISSUE THREAD

**Issue by myszsoda** [openwrt/packages#22451] opened 2023-10-19 15:07 UTC
Maintainer: @BKPepe 
Environment: aarch64, snapshot on 19.10.2023; but issue applies to all versions

Description:
There is a problem with syslog-ng package which has its own logread script to read logs. But this package does conflict with core package logd which has its own logread and it is possible to select both of them.
Thus, I propose to either add CONFLICTS between syslog-ng and logd package or implement PROVIDES for both of them like https://github.com/myszsoda/packages/commit/f680a11fafb1b08f63f96eb5fa2030d12bf7f100

I can implement this, but would like to ask opinion which would be preferred.

**Comment by BKPepe** [comment] 2023-10-19 16:21
Hi,

Hmm, it might works, but that's not a solution. I will look into it.

Dne čt 19. 10. 2023 17:07 uživatel Jakub Raczynski ***@***.***>
napsal:

**Comment by Rondom** [comment] 2024-02-13 14:16
This issue seems to be a duplicate of #11535

I have submitted a PR here. https://github.com/openwrt/packages/pull/23401 It might be more a workaround than solution, but it is better than the current state of things.

**Comment by stokito** [comment] 2024-03-02 21:55
I added a fix for this to my older PR for the syslog-ng https://github.com/openwrt/packages/pull/22763
Please check it.

**Comment by Rondom** [comment] 2024-03-03 00:27
Thanks

**Closed** 2024-11-24 10:10 UTC
