### ISSUE TITLE
nginx musl problem

### ISSUE THREAD

**Issue by lukas2511** [openwrt/packages#1129] opened 2015-04-08 18:35 UTC
The nginx package doesn't build against musl, missing sys/sysctl.h and something about salts, no idea.

I found these patches and tried them (excluding the zlib patch since it wasn't required): https://github.com/mwcampbell/docker-nginx/tree/master/patches

Nginx does compile with those patches and seems to work completely fine.

**Comment by heil** [comment] 2015-04-08 18:53
do you have more information? e.g what plattform, what revision etc.?

**Comment by lukas2511** [comment] 2015-04-08 19:34
Building this with gcc 4.8.x linaro and musl for soc.allwinner.sunxi / Bananapi, but I don't think platform matters since this seems to be just a platform independent problem with nginx and musl.

I'm building the newest trunk version and nginx feed seems to come from this repository, checked out today.

**Comment by nekromant** [comment] 2015-06-21 18:02
I can confirm this on Sunxi A20 Lamobo R1 board.

**Comment by heil** [comment] 2015-06-21 18:07
Please send a dedicated PR that fixes building with musl.

**Comment by heil** [comment] 2015-06-21 19:44
fixed via 9433d5ad285056c9476a899595df6d4785ec127e

**Comment by heil** [comment] 2015-06-22 13:01
@lukas2511  are you fine with that?

**Comment by lukas2511** [comment] 2015-06-22 13:19
didn't have time to test it yet, but looks about right

**Comment by nekromant** [comment] 2015-06-22 14:27
@heil I've tested it yesterday night - nginx now compiles and even works! Thanks a lot! 

P.S. There's still what looks like a musl-related problem with etherwake with some struct redefined, I'll be investigating it today and maybe throw up a patch.

**Comment by Noltari** [comment] 2015-06-22 14:36
@nekromant that's already fixed and waiting for maintainer: https://github.com/openwrt/packages/issues/1381

**Comment by nekromant** [comment] 2015-06-22 14:58
@Noltari Oh, great! Thanks!

**Comment by karlp** [comment] 2015-07-19 12:17
as far as I can tell, all issues reported here are now fixed, ==> closing this ticket.

**Closed by karlp** 2015-07-19 12:17 UTC
